"""Initial schema

Revision ID: ba6bba339e82
Revises: 
Create Date: 2026-07-15 03:05:14.766437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6bba339e82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_sessions', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('simulation_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('simulation_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('simulation_sessions', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('simulation_sessions', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('simulation_sessions', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('simulation_sessions', 'constellation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_sessions', sa.Column('constellation', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('simulation_sessions', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('simulation_sessions', 'longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('simulation_sessions', 'latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('simulation_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('simulation_sessions', 'completed_at')
    op.drop_column('simulation_sessions', 'status')
    # ### end Alembic commands ###
